-- rate_library_in.sql  ·  seed for rate_libraries (market=IN)
-- rate_minor = paise (INR x100), ex-GST. Upserts on (market_code,item_code).
insert into rate_libraries
  (market_code, item_code, item_label, category, unit, rate_minor, tier, region, notes)
values
  ('IN','KIT-MOD-ECO','Modular kitchen — base + wall (laminate)','Modular Joinery','sqft',125000,'economy','metro','Carcass + shutter; hardware basic'),
  ('IN','KIT-MOD-PRM','Modular kitchen — base + wall (acrylic / membrane)','Modular Joinery','sqft',230000,'premium','metro','Soft-close hardware (Hettich/Hafele tier)'),
  ('IN','KIT-MOD-LUX','Modular kitchen — PU / lacquered glass','Modular Joinery','sqft',390000,'luxury','metro','Imported hardware, tall units'),
  ('IN','WDR-OPN-ECO','Wardrobe — openable (laminate)','Modular Joinery','sqft',115000,'economy','metro','BWP/BWR ply carcass'),
  ('IN','WDR-OPN-PRM','Wardrobe — openable (membrane / veneer)','Modular Joinery','sqft',175000,'premium','metro','Internal laminate, drawers'),
  ('IN','WDR-SLD-PRM','Wardrobe — sliding (laminate)','Modular Joinery','sqft',195000,'premium','metro','Slimline sliding channel'),
  ('IN','WDR-SLD-LUX','Wardrobe — sliding (lacquered glass)','Modular Joinery','sqft',310000,'luxury','metro','Profile shutters, LED'),
  ('IN','TVU-STD-PRM','TV unit with paneling','Modular Joinery','sqft',185000,'premium','metro','Storage + back panel'),
  ('IN','CRK-UNIT-PRM','Crockery / display unit','Modular Joinery','sqft',195000,'premium','metro','Glass shutters + profile light'),
  ('IN','STDY-DSK-PRM','Study / work desk unit','Modular Joinery','sqft',165000,'premium','metro','Desk + overhead storage'),
  ('IN','VAN-BATH-PRM','Bathroom vanity (WPC, water-resistant)','Modular Joinery','sqft',180000,'premium','metro','WPC carcass, laminate finish'),
  ('IN','POOJA-UNIT-PRM','Pooja unit (carved / CNC)','Modular Joinery','unit',4500000,'premium','metro','CNC jaali, accent lighting'),
  ('IN','LOFT-STOR-ECO','Loft / overhead storage','Modular Joinery','sqft',95000,'economy','metro','Above wardrobe / kitchen'),
  ('IN','SHOE-RACK-ECO','Shoe rack / foyer unit','Modular Joinery','sqft',105000,'economy','metro','Ventilated shutters'),
  ('IN','CEIL-GYP-ECO','Gypsum false ceiling — plain','False Ceiling','sqft',9000,'economy','metro','Saint-Gobain/India Gypsum board'),
  ('IN','CEIL-GYP-PRM','Gypsum false ceiling — with cove','False Ceiling','sqft',13500,'premium','metro','Incl. cove detailing'),
  ('IN','CEIL-POP-ECO','POP false ceiling — plain','False Ceiling','sqft',8000,'economy','metro','On-site POP punning'),
  ('IN','CEIL-DSGN-LUX','Designer ceiling — multi-level / coffered','False Ceiling','sqft',23000,'luxury','metro','Complex levels + concealed light'),
  ('IN','CEIL-PERI-PRM','Peripheral cove ceiling','False Ceiling','rft',24000,'premium','metro','Running perimeter cove'),
  ('IN','PNT-EML-ECO','Interior emulsion — 2 coats (economy brand)','Painting','sqft',2200,'economy','metro','Incl. 1 coat primer'),
  ('IN','PNT-EML-PRM','Interior emulsion — premium (Royale / Velvet)','Painting','sqft',3800,'premium','metro','Washable, low-VOC'),
  ('IN','PNT-PUTTY-ECO','Wall putty + primer','Painting','sqft',1600,'economy','metro','2 coats putty, sanded'),
  ('IN','PNT-TEX-PRM','Textured / accent finish','Painting','sqft',18000,'premium','metro','Royale Play / metallic'),
  ('IN','PNT-ENML-ECO','Enamel on doors / grills','Painting','sqft',3500,'economy','metro','Surface prep + 2 coats'),
  ('IN','PNT-EXT-PRM','Exterior weatherproof emulsion','Painting','sqft',3000,'premium','metro','Apex/WeatherCoat tier'),
  ('IN','PNL-LAM-PRM','Laminate wall paneling','Wall Paneling','sqft',32000,'premium','metro','On ply backing'),
  ('IN','PNL-VNR-LUX','Veneer paneling (PU finish)','Wall Paneling','sqft',75000,'luxury','metro','Natural veneer + melamine/PU'),
  ('IN','PNL-FLUT-PRM','Fluted / charcoal louver panel','Wall Paneling','sqft',48000,'premium','metro','WPC/MDF fluted'),
  ('IN','PNL-WLP-ECO','Wallpaper — supply + install','Wall Paneling','sqft',14000,'economy','metro','Standard rolls'),
  ('IN','PNL-WLP-LUX','Wallpaper — designer / imported','Wall Paneling','sqft',32000,'luxury','metro','Textured / imported'),
  ('IN','PNL-PVC-ECO','PVC wall panel','Wall Paneling','sqft',16000,'economy','metro','Quick-fit, waterproof'),
  ('IN','FLR-VIT-ECO','Vitrified tiles — supply + lay','Flooring','sqft',11000,'economy','metro','Incl. tile + labour + cement'),
  ('IN','FLR-VIT-PRM','Vitrified tiles — premium (double charge)','Flooring','sqft',17500,'premium','metro','Large-format / GVT'),
  ('IN','FLR-LAM-PRM','Laminate wooden flooring','Flooring','sqft',16500,'premium','metro','AC4, click-lock + underlay'),
  ('IN','FLR-ENG-LUX','Engineered wood flooring','Flooring','sqft',42000,'luxury','metro','Real wood top layer'),
  ('IN','FLR-MRB-LUX','Imported marble — supply + lay','Flooring','sqft',65000,'luxury','metro','Polishing extra'),
  ('IN','FLR-SPC-PRM','SPC / WPC click flooring','Flooring','sqft',14500,'premium','metro','Rigid core, waterproof'),
  ('IN','FLR-SKIRT-ECO','Skirting','Flooring','rft',8500,'economy','metro','Matching tile/laminate'),
  ('IN','ELE-PT-ECO','Electrical point — wiring + modular switch','Electrical','point',48000,'economy','metro','Concealed, FR wire'),
  ('IN','ELE-PT-PRM','Electrical point — premium switches','Electrical','point',85000,'premium','metro','GM/Legrand tier modular'),
  ('IN','ELE-DB-PRM','Distribution board + MCB','Electrical','unit',850000,'premium','metro','8-way, MCB + RCCB'),
  ('IN','ELE-HOME-LUX','Smart home automation point','Electrical','point',320000,'luxury','metro','App/voice controlled'),
  ('IN','LGT-COVE-PRM','Cove / profile LED strip','Lighting','rft',19000,'premium','metro','Strip + driver + profile'),
  ('IN','LGT-SPOT-ECO','Recessed spot / COB light','Lighting','point',55000,'economy','metro','Fixture + install'),
  ('IN','LGT-SPOT-PRM','Recessed spot — premium fixture','Lighting','point',110000,'premium','metro','Anti-glare, tunable'),
  ('IN','LGT-PEND-LUX','Decorative pendant / chandelier point','Lighting','point',250000,'luxury','metro','Fixture cost separate'),
  ('IN','PLB-PT-ECO','Plumbing point (CPVC)','Plumbing','point',95000,'economy','metro','Hot+cold, concealed'),
  ('IN','PLB-PT-PRM','Plumbing point — concealed premium','Plumbing','point',165000,'premium','metro','Astral/Supreme tier'),
  ('IN','SAN-CP-PRM','CP fittings set (premium brand)','Plumbing','set',1800000,'premium','metro','Jaquar tier per bath'),
  ('IN','SAN-WC-PRM','Wall-hung WC + concealed cistern','Plumbing','unit',2200000,'premium','metro','Incl. frame + install'),
  ('IN','PLB-GEYSER-ECO','Geyser point + install','Plumbing','point',140000,'economy','metro','Excl. geyser unit'),
  ('IN','CIV-DEMO-ECO','Wall / structure demolition','Civil','sqft',3500,'economy','metro','Incl. debris removal'),
  ('IN','CIV-BRK4-ECO','Brick wall — 4 inch','Civil','sqft',9500,'economy','metro','With plaster both sides'),
  ('IN','CIV-BRK9-ECO','Brick wall — 9 inch','Civil','sqft',16500,'economy','metro','With plaster both sides'),
  ('IN','CIV-WPF-PRM','Bathroom waterproofing','Civil','sqft',13000,'premium','metro','Membrane + screed'),
  ('IN','CIV-PLAS-ECO','Plastering','Civil','sqft',4500,'economy','metro','12mm internal'),
  ('IN','CIV-DADO-PRM','Wall tiling / dado — supply + lay','Civil','sqft',15000,'premium','metro','Bathroom/kitchen dado'),
  ('IN','GLS-PART-PRM','Toughened glass partition','Glass & Mirror','sqft',65000,'premium','metro','10–12mm, hardware extra'),
  ('IN','GLS-SHWR-PRM','Shower enclosure (toughened)','Glass & Mirror','sqft',75000,'premium','metro','With SS fittings'),
  ('IN','MIR-DECO-PRM','Designer / beveled mirror','Glass & Mirror','sqft',32000,'premium','metro','With backing + fix'),
  ('IN','GLS-BACK-LUX','Back-painted glass (kitchen)','Glass & Mirror','sqft',48000,'luxury','metro','Backsplash application'),
  ('IN','SFT-CURT-PRM','Curtains — supply + install (incl. rod)','Soft Furnishing','sqft',22000,'premium','metro','Fabric + stitching + track'),
  ('IN','SFT-BLND-PRM','Roller / roman blinds','Soft Furnishing','sqft',18000,'premium','metro','Per covered area'),
  ('IN','SFT-UPH-PRM','Upholstery / headboard panel','Soft Furnishing','sqft',65000,'premium','metro','Foam + fabric + ply')
on conflict (market_code, item_code) do update
  set rate_minor = excluded.rate_minor,
      item_label = excluded.item_label,
      category   = excluded.category,
      unit       = excluded.unit,
      tier       = excluded.tier,
      region     = excluded.region,
      notes      = excluded.notes;
